FROM golang:alpine AS builder

RUN apk update && apk add --no-cache git 

RUN mkdir /GoSupervisor

WORKDIR /GoSupervisor

COPY . .

RUN go get -d -u ./...

ENV RABBITMQ_HOST=rabbitmq
ENV POSTGRES_HOST=postgres

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -installsuffix cgo -o /go/bin/GoSupervisor ./cmd/go_supervisor/main.go

FROM scratch

COPY --from=builder /go/bin/GoSupervisor /go/bin/GoSupervisor

ENTRYPOINT ["/go/bin/GoSupervisor"]

EXPOSE 8050